//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalControllerGUI
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class UnitGroup : INotifyPropertyChanged
    {
        private string unitname;
        public int id { get; set; }
        public Nullable<int> UnitNum { get; set; }
        public Nullable<double> CurrentProduction { get; set; }
        public Nullable<double> MaxProduction { get; set; }
        public string UnitName {
            get { return unitname; }
            set { unitname = value; NotifyPropertyChanged(); OnPropertyChanged("UnitName");
            }
        }
        public Nullable<int> lkResId { get; set; }
    
        public virtual UnitGroup UnitGroup1 { get; set; }
        public virtual UnitGroup UnitGroup2 { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null) {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        private void NotifyPropertyChanged([CallerMemberName] String propertyName = "") {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
