//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVM1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitGroup
    {
        public int id { get; set; }
        public Nullable<int> UnitNum { get; set; }
        public Nullable<double> CurrentProduction { get; set; }
        public Nullable<double> MaxProduction { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> lkResId { get; set; }
    
        public virtual UnitGroup UnitGroup1 { get; set; }
        public virtual UnitGroup UnitGroup2 { get; set; }
    }
}
