//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVM1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int id { get; set; }
        public string UnitType { get; set; }
        public Nullable<double> CurrentActivePower { get; set; }
        public Nullable<double> MinimumActivePower { get; set; }
        public Nullable<double> MaximumActivePower { get; set; }
        public string ControlType { get; set; }
        public Nullable<double> ProductionPrice { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
